import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const hikasami = localFont({
  src: "../fonts/variable/Hikasami-VF.woff2",
  variable: "--font-hikasami",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hikasami.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
