import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const family = localFont({
  src: [
    {
      path: "../KlimTestFonts/Test web fonts (Variable, WOFF2)/Test Family/test-family-vf-roman.woff2",
      style: "normal",
    },
    {
      path: "../KlimTestFonts/Test web fonts (Variable, WOFF2)/Test Family/test-family-vf-italic.woff2",
      style: "italic",
    },
  ],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${family.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
